name: qr_scanner
description: "A Flutter application for container tracking."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
     # Firebase Core (must be first)
  firebase_core: ^2.32.0
  
  # Firebase Services - use compatible versions
  cloud_firestore: ^4.17.0
  firebase_auth: ^4.9.0
  firebase_storage: ^11.7.0
  firebase_messaging: ^14.7.0
  firebase_analytics: ^10.7.0
  google_sign_in: ^6.1.6
  cupertino_icons: ^1.0.2
  mobile_scanner: ^4.0.0  # Keep only this one
  http: ^1.1.0
  shared_preferences: ^2.2.2
  google_fonts: ^6.1.0
  qr_flutter: ^4.1.0
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true